# Generated by Django 2.1 on 2019-11-22 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0002_auto_20191122_2128'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntryModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('checkin', models.DateTimeField(auto_now_add=True)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='ExitModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('checkin', models.DateTimeField()),
                ('checkout', models.DateTimeField(auto_now_add=True)),
                ('Description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Host',
            fields=[
                ('name', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('Email', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.AddField(
            model_name='exitmodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Host'),
        ),
        migrations.AddField(
            model_name='entrymodel',
            name='host',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Host'),
        ),
    ]
